### ISSUE TITLE
continuous-deploy-fingerprint produce different runtime version for updates and builds

### ISSUE THREAD

**Issue by vargajacint** [expo/expo-github-action#286]
### Description of the bug
Using the continuous-deploy-fingerprint GitHub Action produces different hash for builds and updates.
Moreover, introducing **js only changes** in the code creates a new EAS build every time, and I think the issue is related.

### To Reproduce
1. Implemented the continuous-deploy-fingerprint GH Action using the example
2. Pushed some JS-only changes (like increasing the loader size)
3. Action started to run: Calculated the fingerprint which was **exactly the same** as the previous one (I compared them using `diff`).
4. New EAS build(sadly) and Update generated
5. Checking the EAS Build runtime-version does not match with the EAS update runtime-version
6. The weird part is that I did this several times, and the EAS build runtime-version was always the same, but somehow it always generated a new build

#### Expected behavior
Do not generate a new EAS build if it's not needed. Generate EAS update only for JS-only change. 
Match the EAS build runtime-version with the EAS update runtime-version.

#### Actual behavior
The EAS build is always triggered, even if it's completely unnecessary. The EAS build runtime version is completely different than the EAS update runtime version

<img width="1920" alt="continuous-deploy-fingerprint" src="https://github.com/expo/expo-github-action/assets/42407460/e9a9303f-b9ab-44c4-88c4-81186f7e70b3">

_As you can see, the update runtime-version is completely different from the build-runtime version (red and blue arrows), even though they were triggered by the same action._
_As you can see the build runtime-version was always the same per platform. So I don't get why new build was triggered then._

**Comment by vargajacint** [comment]
## Investigation vol 1
Here are some logs from the GitHub Action
```bash
... fingerprint generation
{"hash":"4961a8e1e410721c5dca3b1ded6a0e8c49fc9462"}}],"hash":"b1f4f9c5fcf7730b0c212f190c84efacf92bca6f"}
Android fingerprint: 2cffbffcbf2a653286afec2f359d4db392173849 ✅ -> It's okay, as we see before I already had some builds that fingerprint was this
iOS fingerprint: b1f4f9c5fcf7730b0c212f190c84efacf92bca6f ✅ -> It's okay, as we see before I already had some builds that fingerprint was this
Looking for builds with matching runtime version (fingerprint)...
/opt/hostedtoolcache/eas-cli/9.1.0/x64/node_modules/.bin/eas build:list --platform android --status finished --buildProfile preview --runtimeVersion 2cffbffcbf2a653286afec2f359d4db392173849 --limit 1 --json --non-interactive
[] -> 🔴 The problem is that this script looking for **build** with this fingerprint, but somehow the build fingerprint is not same as it was calculated
No existing Android build found for fingerprint, starting a new build...
/opt/hostedtoolcache/eas-cli/9.1.0/x64/node_modules/.bin/eas build --profile preview --platform android --non-interactive --json --no-wait --build-logger-level debug

[
  {
    ...
    "id": "cb3bf3c9-ad88-407b-88a5-88d60e8ce116",
    "channel": "testpreview",
    "distribution": "INTERNAL",
    "buildProfile": "preview",
    "sdkVersion": "51.0.0",
    "appVersion": "0.1.9",
    "appBuildVersion": "1",
    "runtimeVersion": "4db5b01cb43bc22b8b1ed847d4019db600c5537d", -> 🔴 WHY? 
    "gitCommitHash": "f181a8507f134ec947fcbdb9649b1307955ddf48",
    "gitCommitMessage": "test: js only change"
  }
]
```

**Comment by daniel-xyz** [comment]
I'm experiencing the same. When I was just using the runtimeVersion policy `fingerprint` it produced the correct ones. As soon as I started using the github action `continuous-deploy-fingerprint`, the fingerprint of the updates changed while the ones for the builds remained the same as before.

**Comment by daniel-xyz** [comment]
I just experienced the same issue and found the reason for it (see below). When I was just using the runtimeVersion policy "fingerprint," it produced the correct ones. However, as soon as I started using the GitHub Action continuous-deploy-fingerprint, the runtimeVersion of the updates changed, while the ones for the builds remained the same as before.

The issue (at least in my case) was that the environment variables set in the eas.json were not identical to those set in the update. Before, my GitHub Action contained this command:

```
EXPO_APP_ENV="preview" eas update --branch preview --auto --non-interactive
```

I currently have no idea how to set environment variables for updates within continuous-deploy-fingerprint.

If your issue is different, ignore my solution. Maybe it helps someone else then. :)

**Comment by vargajacint** [comment]
Hi @daniel-xyz 

I had the exactly same problem (env mismatch). Here is some tips from @Kudo 

> published `@expo/fingerprint@0.9.0` that support `fingerprint.config.js`
to ignore app.json version from fingerprint, you could try adding fingerprint.config.js with the following content

```
const { SourceSkips } = require('@expo/fingerprint');
/** @type {import('@expo/fingerprint').Config} */
const config = {
  sourceSkips: SourceSkips.ExpoConfigRuntimeVersionIfString | SourceSkips.ExpoConfigVersions,
};
module.exports = config;
```

i didn't update the dependency inside expo-updates, so please try that first by using yarn resolutions or something.

**Comment by daniel-xyz** [comment]
Oh, sorry that I couldn't help, then. 😅 I meant I still have to set the environment variable somehow, anyway. It's not just about fingerprinting. But maybe it's more of a GitHub Actions problem I can figure out.

**Comment by daniel-xyz** [comment]
Oh, sorry that I couldn't help, then. 😅 I meant I still have to set the environment variable somehow, anyway. It's not just about fingerprinting. But maybe it's more of a GitHub Actions problem I can figure out.

**Comment by giorgiofellipe** [comment]
I can confirm it is still an issue, even forcing to the latest version of the related packages.

```
    "@expo/config-plugins": "^8.0.5",
    "@expo/fingerprint": "^0.9.0",
    "expo-updates": "~0.25.17",
```

Reproducible by simply re-running the pipeline without any changes, always generate new builds.

I'm also seeing Runtime Version as "file:fingerprint" on dev client, have you experienced it @vargajacint?

**Comment by giorgiofellipe** [comment]
Ok, looks like it got fixed on `"@expo/fingerprint": "^0.10.0"`!

**Comment by mrahman-go7** [comment]
I am facing a similar issue. In my logs i see `Existing iOS build found with matching fingerprint: some_value_a`

and it runs:
`eas build:list --platform ios --status finished --buildProfile staging --runtimeVersion some_value_a --limit 1 --json --non-interactive`

but then when update runs `eas update --auto --branch staging --non-interactive --json` runs i get a different runtimeVersion "runtimeVersion": "another_value".

Any thoughts on this?

**Comment by brentvatne** [comment]
hey folks, we recommend referring to this guide for debugging discrepancies between fingerprints generated in different environments: https://docs.expo.dev/eas-update/continuous-deployment/#debugging-fingerprint-inconsistencies

**Comment by mrahman-go7** [comment]
@brentvatne i tried this and my fingerprints match both on local and in my github actions. But it seems that when eas update runs i am getting a different runtime version where in fact i am expecting the same version as the fingerprint.

**Comment by kevinschaffter** [comment]
> Oh, sorry that I couldn't help, then. 😅 I meant I still have to set the environment variable somehow, anyway. It's not just about fingerprinting. But maybe it's more of a GitHub Actions problem I can figure out (edit: I did, lol).
> 
> At least I can confirm that I get the same fingerprints now (if the variables are the same), so I can't reproduce your error.

@daniel-xyz How did you end up making sure the envars were the same within the GH action?

**Comment by daniel-xyz** [comment]
@kevinschaffter that was an easy one, I just set them below `env`:

```
      - name: 🚀 Publish update and create a new build if fingerprint changed
        uses: expo/expo-github-action/continuous-deploy-fingerprint@main
        env:
          EXPO_APP_ENV: 'preview'
        with:
          working-directory: ./apps/expo
          profile: 'preview'
          branch: 'preview'
```

**Comment by vanstinator** [comment]
I've added a `fingerprint.config.js` with the following contents:

```js
const { SourceSkips } = require('@expo/fingerprint')

/** @type {import('@expo/fingerprint').Config} */
const config = {
  sourceSkips:
    // eslint-disable-next-line no-bitwise
    SourceSkips.ExpoConfigRuntimeVersionIfString |
    SourceSkips.ExpoConfigVersions,
}

module.exports = config
```

The android build fingerprint on EAS now matches the output of this github action, so subsequent Expo Updates are pulled down successfully.

ios builds on EAS contain a mismatched fingerprint yet. The only difference is in the hashed expoConfig, and when I ran a diff the EAS version contains my `version` property in my `expoConfig`. Is it possible the mac runners in EAS aren't honoring the `fingerprint.config.js` file yet?

**Comment by Kudo** [comment]
@vanstinator interesting! eas should use the same fingerprint from your project. could you share your eas build id that we could further investigate? e.g. https://expo.dev/accounts/XXX/projects/XXX/builds/ee1bad22-a2c6-4c10-8ef2-281ea15980ee, the `ee1bad22-a2c6-4c10-8ef2-281ea15980ee` is the build id.

**Comment by vanstinator** [comment]
@Kudo Sure! `ca4cabef-dfa6-4eae-bcc1-db14c21ca3b8`

**Comment by Kudo** [comment]
@vanstinator we published new `expo-updates@0.25.21` with `@expo/fingerprint@0.10.2` and it should solve the issue for you. thanks for sharing the issue insight for us.

**Comment by vanstinator** [comment]
Thank you!

**Comment by Wolfleader101** [comment]
> @vanstinator we published new `expo-updates@0.25.21` with `@expo/fingerprint@0.10.2` and it should solve the issue for you. thanks for sharing the issue insight for us.


This is still an issue wit the github actions, do you know if/when there will be a fix for these?

**Comment by Kudo** [comment]
@Wolfleader101 could you share your build id?

**Comment by Wolfleader101** [comment]
> @Wolfleader101 could you share your build id?

Hi @Kudo

Here js the iOS build id for example.

ee1bcee0-4c75-437c-b6ad-6570c1391e5f

It seems that it is pushing an update while it's still building, and it will create a build even if the runtime version already exists

**Comment by Kudo** [comment]
@Wolfleader101 thanks for sharing the info. it appears that your build doesn't have inconsistent fingerprint as the screenshot
![Screenshot 2024-07-30 at 1 38 04 PM](https://github.com/user-attachments/assets/a3f1f71a-efe2-43b9-8590-4969af631553)

could you elaborate more toward your problem with inconsistent fingerprints?

**Comment by Wolfleader101** [comment]
> @Wolfleader101 thanks for sharing the info. it appears that your build doesn't have inconsistent fingerprint as the screenshot
> 
> ![Screenshot 2024-07-30 at 1 38 04 PM](https://github.com/user-attachments/assets/a3f1f71a-efe2-43b9-8590-4969af631553)
> 
> 
> 
> could you elaborate more toward your problem with inconsistent fingerprints?

Hi @Kudo,

When the continuous delivery action runs it always generates a new build, even when a build with the runtime version already exists.

On top of that the run time version generated in the expo updates doesn't match


As you can see below there is a mismatch between the update runtime version and app runtime version.

![image](https://github.com/user-attachments/assets/6749338a-b314-4c2d-8a0a-e10bac451c94)![image](https://github.com/user-attachments/assets/16b405ba-b764-425e-9d37-4873611d3d09)

**Comment by Kudo** [comment]
@Wolfleader101 interesting! i may need your [debug log from github action](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging) to further investigate. are you in expo discord server or twitter? maybe we could have a better way to send DM for faster communication.

**Comment by Wolfleader101** [comment]
Hi @Kudo 

sure I’ll send it through on discord for you, feel free to add me :)
My discord username is wolfleader

**Comment by hirbod** [comment]
I know I am very late to this, but this is the same problem I think I reported to you @Kudo at Appjs conf

**Comment by Kudo** [comment]
@hirbod thank to all the feedback from the community, we've fixed many issues since then. on eas build page, we also added logging if we find inconsistent fingerprint as shown at https://github.com/expo/expo-github-action/issues/286#issuecomment-2257511005.
would be good for you to try again. if there's any issues, i would love to pair with you

**Comment by giorgiofellipe** [comment]
@Kudo what @Wolfleader101 reported seems to be related to https://github.com/expo/eas-cli/issues/2448#issuecomment-222918476. Is there any updates on the subject? Thank you!

**Comment by danoc** [comment]
> Ok, looks like the fingerprint check has been fixed on `"@expo/fingerprint": "^0.10.0"`!
> 
> Still seeing `file:fingerprint` on dev client btw.

I am also seeing this. Did you find a fix? Thanks!

**Comment by mikehuebner** [comment]
Am also seeing this on the latest version, not sure why though. Here is my `app.config.ts` setting for runtimeVersion

```
runtimeVersion: {
  policy: 'fingerprint',
}
```

![image](https://github.com/user-attachments/assets/baa053e5-c861-42f5-9d77-e3cbdd4f4be3)

**Comment by kasvith** [comment]
im also seeing this on latest version as well

**Comment by giorgiofellipe** [comment]
Hi @kudo!
This is definitely still happening.
My build id: c5f4b89e-a05d-468d-ac30-11a32813c2d8

**Comment by Kudo** [comment]
sorry for late response.

@kasvith could you share your build id?

@giorgiofellipe your problem could be pnpm installation. i am asking the team if we could improve pnpm support and will get back to you.

**Comment by acunap** [comment]
> Am also seeing this on the latest version, not sure why though. Here is my `app.config.ts` setting for runtimeVersion
> 
> ```
> runtimeVersion: {
>   policy: 'fingerprint',
> }
> ```
> 
> ![image](https://github.com/user-attachments/assets/baa053e5-c861-42f5-9d77-e3cbdd4f4be3)

Did you manage to fix this? We still see this

**Comment by lander854** [comment]
Expo fingerprints is the worst implementation of a bad idea I've ever seen.. just breaks all the time. The runtime version was supposed to be the source of truth for whether to update or not, now there's a random value that keeps changing without reason, and the feature we PAY for doesn't work properly. amazing.
